### ISSUE TITLE
Revisit init thread registration

### ISSUE THREAD

**Issue by ajhconway** [vmware/splinterdb#141]
The init thread has special registration that saves a `malloc` I guess. It feels like an unnecessary optimization and we should revisit this decision and probably have it register itself the normal way.

**Comment by gapisback** [comment]
Fixed by Rob's check-in of PR 

```
20a926d Rob Johnson 5 days ago Thu, 05-Jan-2023, 05:19:10 PM (Authored: Thu, 05-Jan-2023, 05:19:10 PM)
 Robj/task system config (#497)
```
