### ISSUE TITLE
Platformize `snprintf` and add to `poison.h`

### ISSUE THREAD

**Issue by ajhconway** [vmware/splinterdb#298]
`snprintf` is used in `laio.h`, `clockcache.c` and `mini_allocator.c`. This breaks the platform rules and should be poisoned.

**Comment by gapisback** [comment]
Decided in PR meeting that this is probably not needed to be done. (Reconfirmed this with Alex and team.)

If this ever becomes a problem, we can re-open this and fix at a later date.
