### ISSUE TITLE
Nightly test runs are running into seg-faults, suspected due to OS-level OOM-killer, or similar resource issues. Add instrumentation.

### ISSUE THREAD

**Issue by gapisback** [vmware/splinterdb#327]
Nightly test runs are failing on CI-jobs, whereas these tests are seen to run fine on Nimbus-VMs and Fusion-VMs locally. 
The failures are abrupt, for e.g. in [run no. 6.1](https://runway-ci.eng.vmware.com/teams/splinterdb/pipelines/splinterdb/jobs/main-nightly-build-test-gcc/builds/6.1).
```
+ bin/driver_test splinter_test --functionality 10000000 1000 --num-tables 2 --cache-capacity-gib 1 --db-location splinter_test.functionality.db
bin/driver_test: splinterdb_build_version 12eb5e7f
Dispatch test splinter_test
fingerprint_size: 27
fingerprint_size: 27
Running splinter_test with 1 caches
Functional test started with 2 tables
Round i=       0, op= 0, nummsgs =   273840, minkey=27281667, maxkey=86095491, mindelta =    131072, maxdelta=   131088

[...]

Round i=     201, op= 0, nummsgs =     8108, minkey=28471846, maxkey=62018170, mindelta =        -1, maxdelta= 16777215
Round i=     202, op= 0, nummsgs =   100417, minkey=20858260, maxkey=56475987, mindelta =     -1024, maxdelta=    -1023
./test.sh: line 66:   353 Segmentation fault      "$@"
```

Resolution AIs:

- Add instrumentation to `test.sh` to collect OS-info, such as # of CPUs, memory etc.
- Add monitoring script to track memory usage as the tests run, and report a summary line of HWM of memory usages
- Add other troubleshooting instrumentation that can indicate why the tests are failing.

**Comment by rosenhouse** [comment]
@gapisback with #442 merged (fixed #440), this may be fixed too?
