### ISSUE TITLE
Memtables are only half full

### ISSUE THREAD

**Issue by ajhconway** [vmware/splinterdb#389]
### Describe the bug

When setting the `num_extents` memtable config option, the computation assumes that the extents are all full. However, for most workloads, they will be somewhere between half full and full. Empirically on a random insertion workload, I observed them to be roughly half full.

### Reproduction steps

```bash
Add a `platform_log` in `trunk_memtable_incorporate` that prints a sum of the `req->output_pivot_kv_byte_count` statistic.
```

### Expected behavior

Memtables should have roughly `cfg->memtable_capacity` bytes of data when full, by default this is 24MiB.

### Additional context

I think the easier and maybe best fix is just to double the `num_extents` config option in `mt_cfg`. There will be some workloads where this will cause overfull memtables, such as sequential insertion workloads, but I think this is ok.

**Comment by rtjohnso** [comment]
Closing, as I believe PR #390 fixed it.
