### ISSUE TITLE
Assertion failed at src/task.c:951:task_system_get_thread_scratch(): "(tid < MAX_THREADS)". tid=64

### ISSUE THREAD

**Issue by tinoryj** [vmware/splinterdb#629]
Hello,

I set the SplinterDB in the following way:

#include "splinterdb/default_data_config.h"
#include "splinterdb/splinterdb.h"

/* Application declares the limit of key-sizes it intends to use */
#define USER_MAX_KEY_SIZE ((int)100)
#define DB_FILE_SIZE_MB 1024 // Size of SplinterDB device; Fixed when created
#define CACHE_SIZE_MB 64 // Size of cache; can be changed across boots

SplinterDB::SplinterDB(const char* dbfilename, const std::string& config_file_path)
{
    // get SplinterDB config
    default_data_config_init(USER_MAX_KEY_SIZE, &splinterDataCfg_);
    memset(&splinterdbCfg_, 0, sizeof(splinterdbCfg_));
    splinterdbCfg_.filename = dbfilename;
    splinterdbCfg_.disk_size = (DB_FILE_SIZE_MB * 1024 * 1024);
    splinterdbCfg_.cache_size = (CACHE_SIZE_MB * 1024 * 1024);
    splinterdbCfg_.data_cfg = &splinterDataCfg_;
    int createStatus = splinterdb_create(&splinterdbCfg_, &db_);
    if (createStatus != 0) {
        cerr << "Failed to create underlying database, status = " << createStatus << endl;
        throw std::runtime_error("Failed to open underlying database");
    } else {
        cerr << "Successfully created underlying database at path: " << splinterdbCfg_.filename << endl;
    }
}

However, the error message appears when inserting KV pairs with YCSB-C after inserting around 2000 KV pairs.
"Assertion failed at src/task.c:951:task_system_get_thread_scratch(): "(tid < MAX_THREADS)". tid=64"

How can I configure the thread number in SplinterDB or other solutions to fix this bug?

**Comment by tinoryj** [comment]
Hello,

The problem still occurs; when I write KV pairs less than 1 million (e.g., 0.1 M), it does not show the problem, but when the KV pair number is over 1 M, the problem kills the application.
![image](https://github.com/user-attachments/assets/461c3317-8f01-440b-98be-c872ddd8a583)

Thank you so much for your help.

**Comment by rtjohnso** [comment]
Hi Yanjing,

Thanks for the report.

The error indicates that there are more than 64 threads.  Splinter
currently supports only up to 64 threads, including any background
threads.  Did you start more than 64 threads in your experiments?

Best,
Rob

**Comment by tinoryj** [comment]
Thanks for your help; I integrated SplinterDB with YCSB-C, and here's the initialization code:

```c++
#ifdef __cplusplus
typedef bool _Bool;
#endif
extern "C" {
#include "splinterdb/default_data_config.h"
#include "splinterdb/splinterdb.h"
}
/* Application declares the limit of key-sizes it intends to use */
#define USER_MAX_KEY_SIZE ((int)100)
#define DB_FILE_SIZE_MB 1024 // Size of SplinterDB device; Fixed when created
#define CACHE_SIZE_MB 64 // Size of cache; can be changed across boots

SplinterDB::SplinterDB(const char* dbfilename, const std::string& config_file_path)
{
    // get SplinterDB config
    default_data_config_init(USER_MAX_KEY_SIZE, &splinterDataCfg_);
    memset(&splinterdbCfg_, 0, sizeof(splinterdbCfg_));
    splinterdbCfg_.filename = dbfilename;
    splinterdbCfg_.disk_size = (DB_FILE_SIZE_MB * 1024 * 1024);
    splinterdbCfg_.cache_size = (CACHE_SIZE_MB * 1024 * 1024);
    splinterdbCfg_.data_cfg = &splinterDataCfg_;
    int createStatus = splinterdb_create(&splinterdbCfg_, &splinterdb_);
    if (createStatus != 0) {
        cerr << "Failed to create underlying database, status = " << createStatus << endl;
        throw std::runtime_error("Failed to open underlying database");
    } else {
        cerr << "Successfully created underlying database at path: " << splinterdbCfg_.filename << endl;
    }
}
```

This is learned from the example (examples/splinterdb_intro_example.c), and I only set the disk and cache size. After that, I learned from the large insert stress test (tests/unit/large_inserts_stress_test.c) and set the `num_memtable_bg_threads` and `num_normal_bg_threads` to one, but it does not help. 

When I run the YCSB-C, it only runs with one thread, and the total thread number should not exceed 64.

Thanks.

**Comment by rtjohnso** [comment]
I suspect the problem is that you haven't registered the thread with
splinterdb.  In YCSB-C, each thread runs `DelegateClient`, which begins by
calling `db->Init()`.  I'd recommend calling `splinterdb_register_thread`
from your SplinterDB class `Init` method.

BUT!

Even better, use the version of YCSB-C that we have already integrated with
SplinterDB:
   https://github.com/rtjohnso/YCSB-C
It supports lots of SplinterDB settings from the command line.  It also has
several optimizations and other feature enhancements.

Best,
Rob

**Comment by tinoryj** [comment]
Thanks a lot for your help!

Yes. The issue comes from the thread registration. Following your recommendation, I switched to the SplinterDB integrated YCSB-C (https://github.com/rtjohnso/YCSB-C); it works well and performs better than the original one. 

Best,
Yanjing
